apiVersion: v1
kind: Pod
metadata:
  name: forgejo-stack
  labels:
    traefik.enable: 'true'
    traefik.http.routers.forgejo.rule: 'Host(`forgejo.home.lohrenz.me`)'
    traefik.http.routers.forgejo.entrypoints: 'websecure'
    traefik.http.routers.forgejo.tls.certresolver: 'porkbun'
    traefik.http.services.forgejo.loadbalancer.server.port: '3000'
spec:
  containers:
    - name: forgejo
      image: codeberg.org/forgejo/forgejo:14-rootless
      ports:
        - containerPort: 22
          hostPort: 222
          protocol: UDP
      volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: localtime-volume
          mountPath: /etc/localtime
          readOnly: true

  volumes:
    - name: localtime-volume
      hostPath:
        path: /etc/localtime
        type: File
    - name: data-volume
      hostPath:
        path: /home/malte/infra/data/forgejo
        type: Directory
