apiVersion: v1
kind: Pod
metadata:
  name: pihole-stack
  labels:
    traefik.enable: "true"
    traefik.http.routers.pihole.rule: "Host(`pi-hole.home.lohrenz.me`)"
    traefik.http.routers.pihole.entrypoints: "websecure"
    traefik.http.routers.pihole.tls.certresolver: "porkbun"
    traefik.http.services.pihole.loadbalancer.server.port: "80"
  annotations:
    io.podman.annotations.port-handler: "pasta"
spec:
  containers:
    - name: pihole
      image: docker.io/pihole/pihole:latest
      ports:
        - containerPort: 53
          hostPort: 53
          hostIP: 10.0.0.67
          protocol: TCP
        - containerPort: 53
          hostPort: 53
          hostIP: 10.0.0.67
          protocol: UDP
      env:
        - name: TZ
          value: "Europe/Berlin"
        - name: FTLCONF_webserver_api_password
          valueFrom:
            secretKeyRef:
              name: pihole_api_password
              key: secret
        - name: FTLCONF_dns_listeningMode
          value: "ALL"
        - name: FTLCONF_dns_upstreams
          value: "127.0.0.1#5335"
        # - name: PIHOLE_DNS_
        #   value: "127.0.0.1#5335"
        - name: DNSMASQ_USER
          value: "root"
      volumeMounts:
        - name: pihole-config
          mountPath: /etc/pihole
    - name: unbound
      image: docker.io/mvance/unbound:latest
      volumeMounts:
        - name: unbound-config
          mountPath: /opt/unbound/etc/unbound

  volumes:
    - name: pihole-config
      hostPath:
        path: /home/malte/infra/data/pihole
        type: Directory
    - name: unbound-config
      hostPath:
        path: /home/malte/infra/data/unbound
        type: Directory
