apiVersion: v1
kind: Pod
metadata:
  name: technitium-stack
  labels:
    traefik.enable: 'true'
    traefik.http.routers.technitium.rule: 'Host(`technitium.home.lohrenz.me`)'
    traefik.http.routers.technitium.entrypoints: 'websecure'
    traefik.http.routers.technitium.tls.certresolver: 'porkbun'
    traefik.http.services.technitium.loadbalancer.server.port: '5380'
spec:
  containers:
    - name: technitium
      image: docker.io/technitium/dns-server:latest
      ports:
        - containerPort: 53
          hostPort: 53
          protocol: UDP
        - containerPort: 53
          hostPort: 53
          protocol: TCP
      env:
        - name: TZ
          value: 'Europe/Berlin'
        - name: DNS_SERVER_DOMAIN
          value: 'technitium.home.lohrenz.me'
      volumeMounts:
        - name: data
          mountPath: /etc/dns

  volumes:
    - name: data
      hostPath:
        path: /home/malte/infra/data/technitium
        type: Directory
