apiVersion: v1
kind: Pod
metadata:
  name: technitium-stack
  labels:
    traefik.enable: 'true'
    traefik.http.routers.technitium.rule: 'Host(`technitium.home.lohrenz.me`)'
    traefik.http.routers.technitium.entrypoints: 'websecure'
    traefik.http.routers.technitium.tls.certresolver: 'porkbun'
    traefik.http.services.technitium.loadbalancer.server.port: '5380'
spec:
  hostNetwork: true
  containers:
    - name: technitium
      image: docker.io/technitium/dns-server:latest
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: TZ
          value: 'Europe/Berlin'
        - name: DNS_SERVER_DOMAIN
          value: 'technitium.home.lohrenz.me'
        - name: DNS_SERVER_WEB_SERVICE_ENABLE_HTTP
          value: 'true'
        - name: DNS_SERVER_WEB_SERVICE_USE_SELF_SIGNED_CERT
          value: 'true'
        - name: DNS_SERVER_RECURSION
          value: 'AllowOnlyForPrivateNetworks'
        - name: DNS_SERVER_FORWARDERS
          value: ''
      volumeMounts:
        - name: data
          mountPath: /etc/dns

  volumes:
    - name: data
      hostPath:
        path: /home/malte/infra/data/technitium
        type: Directory
