apiVersion: v1
kind: Pod
metadata:
  name: vaultwarden-stack
  labels:
    traefik.enable: "true"
    traefik.http.routers.vaultwarden.rule: "Host(`vault.home.lohrenz.me`)"
    traefik.http.routers.vaultwarden.entrypoints: "websecure"
    traefik.http.routers.vaultwarden.tls.certresolver: "porkbun"
    traefik.http.services.vaultwarden.loadbalancer.server.port: "8080"
spec:
  containers:
    - name: vaultwarden
      image: docker.io/vaultwarden/server:latest
      volumeMounts:
        - name: data-volume
          mountPath: /data

  volumes:
    - name: data-volume
      hostPath:
        path: /home/malte/infra/data/vaultwarden
        type: Directory
